-- vv-scrollbar 默认配置，独立于配置校验与公开类型

local SEV = vim.diagnostic.severity

return {
  enabled = true,
  current_only = false,
  width = 2,
  right_offset = 0,
  min_thumb = 2,
  throttle_ms = 30,
  search_line_limit = 20000,
  excluded_filetypes = {
    'terminal', 'toggleterm', 'blink-cmp-menu', 'cmp_docs', 'cmp_menu',
    'dropbar_menu', 'dropbar_menu_fzf', 'DressingInput', 'noice', 'prompt', 'TelescopePrompt',
    'dashboard', 'vv-explorer', 'vv-git', 'vv-task-panel', 'vv-task-panel-tasks',
  },
  excluded_buftypes = { 'nofile', 'terminal', 'prompt', 'quickfix' },
  window_filter = nil,
  map_view = {
    enabled = true,
    mode = 'viewport',
    width = 'auto',
    min_width = 8,
    max_width = 16,
    width_ratio = 0.14,
    x_multiplier = 4,
    y_multiplier = 1,
    min_thumb = 2,
    max_lines_per_dot = 8,
    tab_width = 'buffer',
    include_whitespace = false,
    debounce_ms = 150,
    max_lines = 50000,
    large_file_behavior = 'scrollbar',
    show_on_short_buffers = true,
    preserve_map_under_thumb = true,
    marker_layout = 'overlay',
    marker_lane_width = 2,
    marker_position = 'right',
    marker_click = 'center',
    cursor = {
      style = 'dots',
      side = 'right',
      width = 1,
      symbol = '▎',
    },
    interaction = {
      edge_scroll = true,
      edge_margin = 2,
      edge_speed = 2,
      edge_interval = 50,
      snap_to_edges = true,
      right_click = 'toggle_view',
    },
    degradation = {
      folds = 'fit',
      wrap = 'viewport',
      diff = 'fit',
    },
    syntax = {
      enabled = true,
      max_lines = 2000,
      max_bytes = 524288,
      max_captures = 30000,
      max_time_ms = 100,
      fallback = 'mono',
      capture_map = {},
    },
  },
  markers = {
    diagnostics = true,
    git = true,
    search = true,
    marks = true,
    quickfix = true,
    cursor = true,
  },
  symbols = {
    thumb = ' ',
    cursor = '█',
    search = '•',
    mark = '◆',
    quickfix = '■',
    diagnostics = {
      [SEV.ERROR] = '●',
      [SEV.WARN] = '●',
      [SEV.INFO] = '●',
      [SEV.HINT] = '●',
    },
    git = {
      A = '▎',
      C = '▎',
      D = '󰆐',
    },
  },
  highlights = {
    track = { bg = '#20242b' },
    separator = { fg = '#20242b', bg = '#20242b' },
    map_view = { fg = '#565f89' },
    map_cursor = { fg = '#7aa2f7' },
    thumb = { bg = '#3b4252' },
    active = { bg = '#5b6478' },
    cursor = { fg = '#7aa2f7' },
    search = { fg = '#ff9e64' },
    mark = { fg = '#bb9af7' },
    quickfix = { fg = '#e0af68' },
    diag_error = { fg = '#f7768e' },
    diag_warn = { fg = '#e0af68' },
    diag_info = { fg = '#7dcfff' },
    diag_hint = { fg = '#1abc9c' },
  },
}
