-- vv-scrollbar 默认配置，独立于配置校验与公开类型

local SEV = vim.diagnostic.severity

return {
  enabled = true,
  current_only = false,
  width = 2,
  right_offset = 0,
  min_thumb = 2,
  throttle_ms = 30,
  search_line_limit = 20000,
  show_on_short_buffers = true,
  cursor = {
    style = 'line',
    side = 'right',
    width = 1,
    symbol = '▕',
  },
  interaction = {
    right_click = 'toggle_view',
    cursor_on_drag = 'follow',
    marker_click = 'center',
  },
  excluded_filetypes = {
    'terminal', 'toggleterm', 'blink-cmp-menu', 'cmp_docs', 'cmp_menu',
    'dropbar_menu', 'dropbar_menu_fzf', 'DressingInput', 'noice', 'prompt', 'TelescopePrompt',
    'dashboard', 'vv-explorer', 'vv-git', 'vv-task-panel', 'vv-task-panel-tasks',
  },
  excluded_buftypes = { 'nofile', 'terminal', 'prompt', 'quickfix' },
  window_filter = nil,
  map_view = {
    enabled = true,
    mode = 'viewport',
    width = 'auto',
    min_width = 8,
    max_width = 16,
    width_ratio = 0.14,
    x_multiplier = 4,
    y_multiplier = 1,
    min_thumb = 2,
    max_lines_per_dot = 8,
    tab_width = 'buffer',
    include_whitespace = false,
    debounce_ms = 150,
    max_lines = 50000,
    large_file_behavior = 'scrollbar',
    preserve_map_under_thumb = true,
    marker_layout = 'right',
    marker_lane_width = 2,
    marker_position = 'right',
    interaction = {
      edge_scroll = true,
      edge_margin = 2,
      edge_speed = 2,
      edge_interval = 50,
      snap_to_edges = true,
    },
    degradation = {
      folds = 'fit',
      wrap = 'viewport',
      diff = 'fit',
    },
    syntax = {
      enabled = true,
      max_lines = 2000,
      max_bytes = 524288,
      max_captures = 30000,
      max_time_ms = 100,
      fallback = 'mono',
      capture_map = {},
    },
  },
  markers = {
    diagnostics = true,
    git = true,
    search = true,
    marks = true,
    quickfix = true,
    cursor = true,
  },
  symbols = {
    thumb = ' ',
    cursor = '█',
    search = '•',
    mark = '◆',
    quickfix = '■',
    diagnostics = {
      [SEV.ERROR] = '●',
      [SEV.WARN] = '●',
      [SEV.INFO] = '●',
      [SEV.HINT] = '●',
    },
    git = {
      A = '▎',
      C = '▎',
      D = '󰆐',
    },
  },
  highlights = {
    track = { bg = 'bg' },
    separator = { fg = 'bg', bg = 'bg' },
    map_view = { link = 'Comment' },
    map_cursor = { link = 'CursorLineNr' },
    thumb = { link = 'CursorLine' },
    active = { link = 'Visual' },
    cursor = { link = 'CursorLineNr' },
    search = { link = 'Search' },
    mark = { link = 'Special' },
    quickfix = { link = 'QuickFixLine' },
    diag_error = { link = 'DiagnosticError' },
    diag_warn = { link = 'DiagnosticWarn' },
    diag_info = { link = 'DiagnosticInfo' },
    diag_hint = { link = 'DiagnosticHint' },
  },
}
